# Site settings
title: LcKamal
email: lckamal@hotmail.com
description: Here I will host some demo sites that I think are worth sharing.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://lckamal.github.io" # the base hostname & protocol for your site
url: "http://lckamal.github.io" # the base hostname & protocol for your site
twitter_username: lckamal
github_username:  lckamal
facebook_username:  lckamal


# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]